jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - coverage-reporter/send_report:
          coverage-reports: clover.xml
          project-token: $CODACY_PROJECT_TOKEN
          skip: true
orbs:
  coverage-reporter: codacy/coverage-reporter@11.3.1
version: 2.1
