version: 2.1
orbs:
  snyk: snyk/snyk@0.0.12
  node: circleci/node@4.0.0
workflows:
  node-tests:
    jobs:
      - node/test
  snyk-scanning:
    jobs:
      build:
        docker:
          - image: 'circleci/node:4.8.2'
        steps:
          - checkout
          - run: npm install -q
          - snyk/scan
          
