version: 2.1
orbs:
  node: circleci/node@4.0.0
  coverage-reporter: codacy/coverage-reporter@11.3.1
jobs:
  codacy-report:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - coverage-reporter/send_report:
          coverage-reports: 'lcov.info, clover.xml'
          project-token: CODACY_PROJECT_TOKEN
workflows:
  node-tests:
    jobs:
      - node/test
      - codacy-report:
        requires:
          - node/test
