version: 2.1
orbs:
  node: circleci/node@4.0.0
  coverage-reporter: codacy/coverage-reporter@11.3.1
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
        cache-path: ~/project/node-modules
        override-ci-command: npm install
      - run: npm run test -- --coverage
      - coverage-reporter/send_report:
          coverage-reports: 'lcov.info, clover.xml'
          project-token: CODACY_PROJECT_TOKEN
workflows:
  test-and-coverage:
    jobs:
      - test
