jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
  repa:
    docker:
      image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: npm run test -- --coverage
      - coverage-reporter/send-report:
          coverage-reports: coverage/clover.xml
          project-token: CODACY_TOKEN
orbs:
  node: circleci/node@4.0.0
  coverage-reporter: codacy/coverage-reporter@11.3.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
      - repa:
          requires:
            - test
