version: 2.1
orbs:
  node: circleci/node@4.0.0
  snyk: snyk/snyk@0.0.12
jobs:
  build:
    docker:
      - image: 'circleci/node:14.9.0'
    steps:
      - checkout
      - run: npm install -q
      - snyk/scan:
        token-variable: SNYK_TOKEN
workflows:
  test-and-scan:
    jobs:
      - node/test
      - build
