jobs:
  build:
    docker:
      image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: npm run test -- --coverage
      - coverage-reporter/send-report:
          coverage-reports: coverage/clover.xml
          project-token: CODACY_TOKEN
orbs:
  coverage-reporter: codacy/coverage-reporter@11.3.1
version: 2.1
workflows: null
