jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      #- run: npm run test -- --coverage
      - run:
          name: JUnit reporter
          command: npm run test:ci -- --coverage
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results/junit/
      - store_test_results:
          path: test-results/junit/
      - coverage-reporter/send_report:
          coverage-reports: coverage/clover.xml,coverage/lcov.info
          project-token: $CODACY_PROJECT_TOKEN
      - store_artifacts:
          path: test-results
orbs:
  coverage-reporter: codacy/coverage-reporter@11.3.1
  node: circleci/node@4.0.0
version: 2.1
