jobs:
  codacy-coverage-report:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: npm run test -- --coverage
      - coverage-reporter/send_report:
          coverage-reports: 'report.xml,coverage.info'
          project-token: CODACY_TOKEN
orbs:
  coverage-reporter: codacy/coverage-reporter@11.3.1
version: 2.1
